### ISSUE TITLE
Crash when app targeting Android 8

### ISSUE THREAD

**Issue by MaryiaR** [auth0/Lock.Android#483]
Hi,
My app crashes on launch after updating targetSdkVersion and support libs version to 28:

java.lang.NoSuchMethodError: No virtual method setOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.verifone.curb.driver.dev-1/base.apk:classes5.dex)
        at com.auth0.android.lock.views.ModeSelectionView.init(ModeSelectionView.java:57)
        at com.auth0.android.lock.views.ModeSelectionView.<init>(ModeSelectionView.java:45)
        at com.auth0.android.lock.views.FormLayout.init(FormLayout.java:94)
        at com.auth0.android.lock.views.FormLayout.<init>(FormLayout.java:80)
        at com.auth0.android.lock.views.ClassicLockView.showContentLayout(ClassicLockView.java:116)
        at com.auth0.android.lock.views.ClassicLockView.init(ClassicLockView.java:91)
        at com.auth0.android.lock.views.ClassicLockView.configure(ClassicLockView.java:177)
        at com.auth0.android.lock.LockActivity$3$1.run(LockActivity.java:459)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Lock version - 2.10.0

Could you please take a look and help me with this?

**Comment by lbalmaceda** [comment]
I'm aware of this and I'm working on updating our release plugin first. Once that's done I can update the SDKs to use latest SDK version (28). That should fix the issue, since I checked and the method was not removed but deprecated on the support library version 26. There are a few PRs open related to this but I'll leave this one open for tracking purposes 👌
